name: deploy_mkdocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Deploy mkdocs"
          commit_options: "--no-verify"
